-- Migration: Add R&D Artifacts Storage
-- Created: 2026-03-16
-- Purpose: Store POC code, research documents, and Nuclei templates generated by R&D experiments

-- Artifact storage for R&D experiment outputs
CREATE TABLE IF NOT EXISTS rd_artifacts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  experiment_id UUID NOT NULL REFERENCES rd_experiments(id) ON DELETE CASCADE,
  project_id UUID NOT NULL REFERENCES research_projects(id) ON DELETE CASCADE,
  
  -- Artifact metadata
  artifact_type TEXT NOT NULL CHECK (artifact_type IN ('research_document', 'poc_code', 'nuclei_template', 'tool_binary')),
  filename TEXT,
  language TEXT, -- python, ruby, yaml, markdown, bash, powershell
  
  -- Content storage
  content TEXT, -- Source code or document text
  file_path TEXT, -- Path if stored on filesystem
  file_size INTEGER, -- Size in bytes
  file_hash TEXT, -- SHA256 hash for integrity
  
  -- Metadata
  metadata JSONB DEFAULT '{}'::jsonb,
  tags TEXT[] DEFAULT '{}',
  
  -- Audit
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_rd_artifacts_experiment ON rd_artifacts(experiment_id);
CREATE INDEX idx_rd_artifacts_project ON rd_artifacts(project_id);
CREATE INDEX idx_rd_artifacts_type ON rd_artifacts(artifact_type);

-- Link Tool Registry to R&D artifacts (for tool promotion)
ALTER TABLE tool_registry ADD COLUMN IF NOT EXISTS rd_artifact_id UUID REFERENCES rd_artifacts(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_tool_registry_rd_artifact ON tool_registry(rd_artifact_id);

-- Link vulnerabilities to registered tools (for tracking which vulnerabilities led to which tools)
ALTER TABLE vulnerabilities ADD COLUMN IF NOT EXISTS tool_registered_id UUID REFERENCES tool_registry(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_vulnerabilities_tool_registered ON vulnerabilities(tool_registered_id);

-- Add artifact count to research projects for dashboard display
ALTER TABLE research_projects ADD COLUMN IF NOT EXISTS artifact_count INTEGER DEFAULT 0;

-- Function to update artifact count
CREATE OR REPLACE FUNCTION update_research_project_artifact_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE research_projects
    SET artifact_count = artifact_count + 1
    WHERE id = NEW.project_id;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE research_projects
    SET artifact_count = GREATEST(0, artifact_count - 1)
    WHERE id = OLD.project_id;
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- Trigger to automatically update artifact count
CREATE TRIGGER trigger_update_artifact_count
AFTER INSERT OR DELETE ON rd_artifacts
FOR EACH ROW
EXECUTE FUNCTION update_research_project_artifact_count();

-- Comments for documentation
COMMENT ON TABLE rd_artifacts IS 'Storage for R&D experiment outputs: research documents, POC code, Nuclei templates';
COMMENT ON COLUMN rd_artifacts.artifact_type IS 'Type of artifact: research_document, poc_code, nuclei_template, tool_binary';
COMMENT ON COLUMN rd_artifacts.metadata IS 'Additional metadata specific to artifact type (findings, dependencies, reliability, etc.)';
