import fs from "fs/promises";
import path from "path";
// import puppeteer from "puppeteer"; // NOTE: Requires: npm install puppeteer

const UPLOAD_DIR = process.env.UPLOAD_DIR || "./uploads";
const REPORTS_DIR = path.join(UPLOAD_DIR, "reports");

export async function generateMarkdownReport(
  reportData: any,
  template?: any
): Promise<{ filePath: string; fileSize: number }> {
  // Ensure uploads directory exists
  await fs.mkdir(UPLOAD_DIR, { recursive: true });

  // Generate filename
  const timestamp = Date.now();
  const sanitizedName = reportData.name.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  const filename = `${sanitizedName}_${timestamp}.md`;
  const filePath = path.join(UPLOAD_DIR, filename);

  // Generate markdown content based on report type
  const content = generateReportContent(reportData, template);

  // Write file to disk
  await fs.writeFile(filePath, content, "utf-8");

  // Get file size
  const stats = await fs.stat(filePath);

  return {
    filePath: filename, // Store relative path
    fileSize: stats.size,
  };
}

function generateReportContent(reportData: any, _template?: any): string {
  const { name, type, format } = reportData;
  const date = new Date().toLocaleString();

  // Check if AI-generated content exists (from Technical Writer agent)
  if (reportData.content?.markdown) {
    // Use the AI-generated markdown content directly
    return reportData.content.markdown;
  }

  // Fallback to template-based generation if no AI content
  let content = `# ${name}\n\n`;
  content += `**Report Type:** ${type}\n\n`;
  content += `**Format:** ${format}\n\n`;
  content += `**Generated:** ${date}\n\n`;
  content += `---\n\n`;

  // Generate content based on report type
  switch (type) {
    case "bug_bounty":
      content += generateBugBountyReport(reportData);
      break;
    case "vulnerability_assessment":
      content += generateVulnerabilityReport(reportData);
      break;
    case "penetration_test":
      content += generatePenTestReport(reportData);
      break;
    case "operation_summary":
      content += generateOperationSummary(reportData);
      break;
    case "executive_summary":
      content += generateExecutiveSummary(reportData);
      break;
    default:
      content += generateGenericReport(reportData);
  }

  return content;
}

function generateBugBountyReport(_data: any): string {
  return `## Executive Summary

This bug bounty report documents security vulnerabilities discovered during testing.

## Vulnerability Details

### Severity Classification
- **Critical**: Immediate action required
- **High**: Should be addressed urgently
- **Medium**: Should be addressed in planned updates
- **Low**: Address when convenient

## Proof of Concept

Detailed steps to reproduce the vulnerabilities will be documented here.

## Impact Assessment

### Business Impact
The discovered vulnerabilities could potentially impact:
- Data confidentiality
- System integrity
- Service availability

## Remediation Steps

### Short-term Mitigations
1. Implement immediate security patches
2. Review access controls
3. Monitor for exploitation attempts

### Long-term Solutions
1. Code review and refactoring
2. Security testing integration
3. Regular security audits

## Timeline

- **Discovery Date:** ${new Date().toLocaleDateString()}
- **Report Date:** ${new Date().toLocaleDateString()}
- **Recommended Fix Date:** ${new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toLocaleDateString()}

## References

- OWASP Top 10
- CWE/SANS Top 25
- NIST Cybersecurity Framework

---

*This report was automatically generated by RTPI*
`;
}

function generateVulnerabilityReport(_data: any): string {
  return `## Vulnerability Assessment Summary

This report provides an overview of identified security vulnerabilities.

## Scope

The assessment covered:
- Network infrastructure
- Web applications
- API endpoints
- Authentication mechanisms

## Findings Summary

### By Severity
- Critical: 0
- High: 0
- Medium: 0
- Low: 0
- Informational: 0

## Detailed Findings

Vulnerabilities will be listed here with detailed descriptions, impact analysis, and remediation guidance.

## Recommendations

1. Prioritize critical and high severity vulnerabilities
2. Implement security best practices
3. Regular security assessments
4. Security awareness training

---

*Generated by RTPI on ${new Date().toLocaleString()}*
`;
}

function generatePenTestReport(data: any): string {
  return `## Penetration Test Report

### Engagement Overview

**Test Type:** ${data.type}
**Test Date:** ${new Date().toLocaleDateString()}

## Methodology

The penetration test followed industry-standard methodologies:
1. Reconnaissance
2. Scanning and Enumeration
3. Vulnerability Analysis
4. Exploitation
5. Post-Exploitation
6. Reporting

## Executive Summary

This section provides a high-level overview of the penetration test results.

## Technical Findings

Detailed technical findings will be documented here.

## Risk Assessment

Each finding is classified by severity and likelihood of exploitation.

## Remediation Roadmap

Priority-based remediation steps are provided.

---

*Penetration Test Report Generated by RTPI*
`;
}

function generateOperationSummary(data: any): string {
  return `## Operation Summary: ${data.name}

### Operation Details

**Operation Type:** ${data.type}
**Date:** ${new Date().toLocaleDateString()}

## Objectives

The primary objectives of this operation were:
1. Objective 1
2. Objective 2
3. Objective 3

## Activities Performed

### Reconnaissance
- Information gathering
- Target identification

### Assessment
- Vulnerability scanning
- Manual testing

### Exploitation
- Validated findings
- Demonstrated impact

## Results

Summary of operation results and key findings.

## Recommendations

Next steps and recommendations based on operation results.

---

*Generated by RTPI*
`;
}

function generateExecutiveSummary(_data: any): string {
  return `## Executive Summary

### Overview

This executive summary provides a high-level overview of security assessment findings.

### Key Findings

- Finding 1
- Finding 2
- Finding 3

### Business Impact

The identified issues may impact:
- Operational security
- Data protection
- Regulatory compliance

### Recommendations

1. Address critical vulnerabilities immediately
2. Implement security controls
3. Ongoing security monitoring

### Conclusion

Summary and next steps.

---

*Executive Summary Generated by RTPI on ${new Date().toLocaleDateString()}*
`;
}

function generateGenericReport(data: any): string {
  return `## ${data.name}

**Type:** ${data.type}
**Format:** ${data.format}
**Generated:** ${new Date().toLocaleString()}

## Content

This is a generic report template. Content will be populated based on the specific report type.

## Data

Report data and findings will be displayed here.

---

*Report generated by RTPI*
`;
}

export async function getReportFilePath(filename: string): Promise<string> {
  return path.join(UPLOAD_DIR, filename);
}
